#!/bin/bash
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Runs mount-passthrough with minijail0 as chronos.

set -e

if [ $# -ne 6 ]; then
  echo "Usage: $0 source dest fuse_umask fuse_uid fuse_gid"\
    "android_app_access_type"
  exit 1
fi

. /usr/share/arc/mount-passthrough-jailed-utils.sh

# Run mount-passthrough with minijail0 as chronos, inherit supplementary groups,
# and do not grant CAP_DAC_OVERRIDE, nor force group access permission.
# TODO(b/123669632): Remove the argument |force_group_permission| and related
# logic once we start to run the daemon as MediaProvider UID and GID from
# mount-passthrough-jailed-play.
run_mount_passthrough_with_minijail0 "$@" chronos chronos "true" "false" "false"
